### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by MahmoudAbdelRahman** [MahmoudAbdelRahman/ANT#1]
Here is a list of tasks to be finished for the upcoming release: 
Adding the following components: 
#### Support Vector Machines
- [x] **Support Vector Classifier.**
- [x] **Nu-Support Vector Classification.**
- [x] **Linear Support Vector Classification.**
- [x] **Epsilon-Support Vector Regression.**
- [x] **Linear Support Vector Regression.** -- Needs revision -- 
- [x] **Nu Support Vector Regression.**
- [x] **Unsupervised Outlier Detection. [OneClassSVM]**
--------------
#### Nearest Neighbors.
- [ ] NearestNeighbors (Unsupervised learner for implementing neighbor searches.)
- [ ] KNeighborsClassifier (Classifier implementing the k-nearest neighbors vote.)
- [ ] RadiusNeighborsClassifier (Classifier implementing a vote among neighbors within a given radius)
- [ ] KNeighborsRegressor ( Regression based on k-nearest neighbors. )
- [ ] RadiusNeighborsRegressor (Regression based on neighbors within a fixed radius)
- [ ] NearestCentroid (Nearest centroid classifier.)
- [ ] BallTree (BallTree for fast generalized N-point problems)
- [ ] KDTree (KDTree for fast generalized N-point problems)
----
- [ ] Naive Bayes
- [ ] Decision Trees
- [ ] Random Forests
- [ ] Neural Network
- [ ] Gaussian Processes
- [ ] AdaBoost

**Comment by MahmoudAbdelRahman** [comment]
neat icons need to be designed
![supportvectormachines](https://user-images.githubusercontent.com/6969514/27063863-8851a24c-4ff4-11e7-9120-02a144787e53.png)

**Comment by Jonydeere1** [comment]
Hi! Thank's for this Tool !!! Im user of Gh AND THIS AWESOME!!! 

The Boxes that are not cheked... Are soported in GH pluguin?????
